### ISSUE TITLE
add Instante namespace to Doctrine metadata

### ISSUE THREAD

**Issue by artemevsin** [instante/skeleton#10]
To use `Instante\Doctrine\Users\UserStorage` (which set as default) it is necessarily to add this line to database.neon into doctrine/metadata section. Otherwise Doctrine does not see superclass `\Instante\Doctrine\Users\User` and cannot generate schema for it

`Instante: %paths.root%/vendor/instante/`

**Comment by richard-ejem** [comment]
Thanks for report, this will have to be looked into a bit deeper. Personally I don't use explicit path mapping for doctrine entities (no metadata section), then doctrine (probably kdyby wrapper) does find all my entities in project, including User superclass, even without the line you suggested to add.

However I've also noticed that when I add metadata section with explicit mapping, I have to map everything then (some kind of the default "search everywhere" behavior is overridden).

I welcome any suggestions how to solve this, my best idea is currently to put your suggested code into database.neon commented out with explanation that you have to uncomment the line only when using explicit entity path mapping.

**Comment by artemevsin** [comment]
I'm not sure, but there must be at least one line in metadata (if there is no metadata section, Doctrine will find only entities, that are in `vendor/kdyby/doctrine/src/Kdyby/Doctrine/Entities` [source here](https://github.com/Kdyby/Doctrine/blob/v3.0.1/src/Kdyby/Doctrine/DI/OrmExtension.php#L318)

I just tried remove my metadata section and orm:info shows me only these entities. I have Doctrine v3.0.1

**Comment by richard-ejem** [comment]
Look at https://github.com/Kdyby/Doctrine/blob/v3.0.1/src/Kdyby/Doctrine/DI/OrmExtension.php#L323 - there, when metadata section is not specified, it looks for entities in and only in appDir by default (superclasses from libs are processed as well).
Maybe you have some other metadata defined by another extension, which overrides the default even when no metadata section is in config.

Still I agree that Instante should offer a solution for this, but it should preserve the default behavior by default.

**Comment by artemevsin** [comment]
I think I've found a reason, why empty metadata does not work for me.
If you look at [Configurator::getDefaultParameters()](https://github.com/nette/bootstrap/blob/master/src/Bootstrap/Configurator.php#L135), where appDir is defined, in `$trace[1]['file']` I have `/vendor/instante/bootstrap/src/Bootstrapper.php`, so my %appDir% is  `/vendor/instante/bootstrap/src` instead of `/app` because it takes dir from debug_backtrace and previous step is not `bootstrap.php` but `Bootstrapper.php`

**Comment by richard-ejem** [comment]
Well, that is definitely a bug :) thanks for investigation, I will fix this ASAP as broken appDir is quite serious (weird that we haven't noticed this yet on other projects, probably because Bootstrapper is quite new component of Instante, not used in our older projects...)

**Comment by richard-ejem** [comment]
Bug fixed in instante/bootstrap 1.0.1
Added comment about metadata in b91317d

Closing this for now
