### ISSUE TITLE
User authenticator

### ISSUE THREAD

**Issue by superjija** [instante/skeleton#2]
Add name to example User entity.
I recommend to use anouther column name instead of "name" column in authenticator, e.g. username. Name is necessary column in applications where aren't firstname and lastname separated.

**Comment by richard-ejem** [comment]
Good point, but more likely we'd like to use e-mail as username, as most modern applications do.
Pull request welcomed :)

**Comment by superjija** [comment]
Not everyone wants to use email. Username is more general. You can fill it with anything. E.g. on phone can be writing email so slow...

**Comment by richard-ejem** [comment]
Well for the example user it's not that important, as the end user may change it anyhow. So yes, I'd accept "name" too :)

**Comment by richard-ejem** [comment]
Made user login identifier column name customizable in Authenticator (default is "name") in instante/doctrine 1.1.3 .
Also added sample name column in https://github.com/instante/skeleton/commit/264b54de52ade904f06c6c2bb08be83e740c67ac
